Fix crash introduced by previous cset 7b01294f336d
when types are actually yams schema instead of bare string, one ended up with:

  File "/usr/lib/python2.7/dist-packages/rql/nodes.py", line 639, in get_type
    if lhstype == rhstype and not 'Date' in lhstype:
  TypeError: argument of type 'CubicWebEntitySchema' is not iterable